export const config = [
  {
    icon:'/images/menu/资产查询.png',
    text:'资产查询',
    path:'assetlist',
  },
  {
    icon:'/images/menu/期待.png',
    text:'验收查询',
    path:'验收查询',
  },
  {
    icon:'/images/menu/期待.png',
    text:'资产新增',
    path:'assetcreate',
  },
  {
    icon:'/images/menu/期待.png',
    text:'资产调拨',
    path:'资产调拨',
  },
  {
    icon:'/images/menu/期待.png',
    text:'资产报表',
    path:'资产报表',
  },
  {
    icon:'/images/menu/期待.png',
    text:'设备申请',
    path:'设备申请',
  },
  {
    icon:'/images/menu/期待.png',
    text:'资产变更',
    path:'资产变更',
  },
  {
    icon:'/images/menu/期待.png',
    text:'预算查询',
    path:'预算查询',
  },
  {
    icon:'/images/menu/期待.png',
    text:'合同查询',
    path:'合同查询',
  }
]
