export const config = [
  {
    icon:'/images/menu/资产查询.png',
    text:'资产查询',
    path:'assetlist',
  },
  {
    icon:'/images/menu/验收查询.png',
    text:'验收查询',
    path:'checksearch',
  },
  {
    icon:'/images/menu/资产新增.png',
    text:'资产新增',
    path:'assetcreate',
  },
  {
    icon:'/images/menu/资产调拨.png',
    text:'资产调拨',
    path:'assetallocation',
  },
  {
    icon:'/images/menu/资产报表.png',
    text:'资产报表',
    path:'资产报表',
  },
  {
    icon:'/images/menu/设备申请.png',
    text:'设备申请',
    path:'设备申请',
  },
  {
    icon:'/images/menu/资产变更.png',
    text:'资产变更',
    path:'资产变更',
  },
  {
    icon:'/images/menu/预算查询.png',
    text:'预算查询',
    path:'预算查询',
  },
  {
    icon:'/images/menu/合同查询.png',
    text:'合同查询',
    path:'合同查询',
  }
]
