export const config = [
  {
    icon:'/images/menu/资产查询.png',
    text:'资产查询',
    path:'assetlist',
    key:'assetList'
  },
  {
    icon:'/images/menu/验收查询.png',
    text:'验收查询',
    path:'checksearch',
    key:'checkSearch',
  },
  {
    icon:'/images/menu/资产新增.png',
    text:'资产新增',
    path:'assetcreate',
    key:'assetCreate',
  },
  {
    icon:'/images/menu/资产调拨.png',
    text:'资产调拨',
    path:'assetallocation',
    key:'assetAllocation',
  },
  {
    icon:'/images/menu/资产报表.png',
    text:'资产报表',
    path:'assetReport',
    key:'assetReport',
  },
  {
    icon:'/images/menu/设备申请.png',
    text:'设备申请',
    path:'equipmentApply',
    key:'equipmentApply'
  },
  {
    icon:'/images/menu/资产变更.png',
    text:'资产变更',
    path:'assetChange',
    key:'assetChange'
  },
  {
    icon:'/images/menu/预算查询.png',
    text:'预算查询',
    path:'budgetSearch',
    key:'budgetSearch'
  },
  {
    icon:'/images/menu/合同查询.png',
    text:'合同查询',
    path:'contractSearch',
    key:'contractSearch'
  },
  {
    icon:'/images/menu/资产处置.png',
    text:'资产处置',
    path:'assetDispose',
    key:'assetDispose'
  },{
    icon:'/images/menu/公告消息.png',
    text:'公告消息',
    path:'announcement',
    key:'announcement'
  }
]
